language: java

jdk:
  - openjdk18

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: eH/5FliJUZL8S+lHSBRDu3xmnMLNYJuanhuxJ0Kuwvp1rmDHOgGW/1kXgjqG/w3jAfyo8GzBrrus/9aHY9xvJ5Gn2tZoYdAzaSXfRCsFUDoOemMCwtcHpCnt6NzDLdzYZz+WPdrWYiF7KguzCcY/9nSCP5Wt6QzdHr2rQ2M3UGgN69pVpuzNGWPlq8SVZOZLDEwY+gS01O/1S1pwH5f53SRjPuqNDWPveqV+mTTVHJZR9ChdP0HxeFKKL+Tt8vTiABaZDqX8AJNVbobjwZ3jAjKGyuhgNP2plzt8WZGqptsSUWpcYHvjdFiGR1U8+tW5B4Od7xeZl41dWhSeM6AQ67xMwMvJsQXms3v0f4iXVfdyABMr1YtX2FZoylqyElbmFKxYk7JsjlXGEZo4KB9eWcf65J/lMtw9FfRjYwhS1LZsndzs3AwX9JodzwWeHXTDVovINU+Q8Lpiv8lglMTBkBLOilr/CIuCqDE8K4Hzj9AIfvl8YZzsvaT8fEJqZ9oYa6GrRh266GNF9GUtgyHHhbunFLCO+2c+r79m95j4mvGaNEBeSOcbAGCIi9+cXr0uzDax9+P5lHM3PmqsxAMtZ4Y+uV6sm8lY0oL1Q1luQXXqDdezDKkzFaZPvyRCkLFZSe9U7BGd7G/zssKzB+Nuz/1B2EmayVT08yUhnHYc2tE=
    - secure: WhBUV64lWJCAzJ4lNKqg+9Lswb04qpZa+nfOTpYX5SwimoGPEnaLVe/Q1Z1eyigUk3bXgniy3Xh2LMfABgmDe+OBgMz0DYNCBG3sE7fI4LGKj/cXUaHgk/w1Sw7mYDCXsRyj8u4mLUAXae6nR3wVNkw52EcJtv/WyDIgL0Jriu/LOwutljU1OOvCjhWlLQMgb4TLR7ev0KqlmEEA8b/Tc2Hq/3Gy1Pv/UhfXs4j3QFGnI2I8y59scIa3X2RdaMqI+xnz6p4X34amc/s+nRrhYdh2J6W/+DR8oxlpJFkm0IRvWJWGRrvDUgbNGwbWerRr0ZxIx8QviZVfASjA5BCsNj2cYG4vnOfZj8XOco1fs3awDGoz7EEUvZvfX0iwYqATYsRqbz8m9feTzyzQwfvqVvlN0CxbtCtLzTwf2t35GubnAhB5G5Mfi4A0rrB2WbHj7Tb8deFqzr8MXrKdXwTgVc6AaX0wVX+VwB9gzo0WG3rzZCQyJK+Nej6Nr1hfJPJl3ZLXsKt0Zpc+bNURA2/t6KUzek5wITz30z3BpTf3jAHNabE5oenyLsAXCxHpG8HlyBXqPJBv+4itv7mwFS83fHlhLkPD7JmzG+6T7UwcIZL0TCTBQJGHfjqrMO4+qse0MfIty7Dd9nHGWLRWk6hh2VIOuWtgROGN0cvv8btKAvM=
    - secure: BilXz7uhWsXyvLYG67Blf4M1w1ecijH0oE28rKe3yfJ9Klc9JhmvWFvNh7HZEhJJ68TGTFQM21MBtjZz0FR1tE2jI7WqfWgRdpmUveP4Zml2S+M/4tIE2KiKZkKlt44zYCpsg0WnMhHlli6V2VdkSEkZhHYpu2Kr/+gUvFd+BLIgRYBL02K66OMH/cjJkdoKY07ltRtGgAwbJaUUAytKllxVUyoSWeLRy1SvM8AokMAHNHUgY2eKUdtKcpmV4czQdAGHJxEjzhBFFFB3zkNJT/z+8RbfUZyU+Cgpmc28qZzJqus63E9mlc96qJgnL+kRoaRxmQSR+65s73xor5tUt2PBnLv+qd3KpEOuLi5quXkKlwWp59TUgxg76BSVm1ISmTJ1vv9lJgQgH3cGUOj1lIJ1QBpDdRiMdZMpRej8F5pNpXC4c83kHWtbTPSuSg9tUXIJw8F6whFhqY0w88dm5zV3KKkDzkHN+22kDaVgJYgVRhWaXa/RA9ELSwVZX5OsPekI8/nfxXjLhQJdaUSRbQcg/0GCBbizKdGB9/tH4Pl+Mp6RRdkqT3Hzz9MheMv5EEQ5cIbqBPFwW1Q3xczay8DRyXJQVeiiDnHrKrDVbngVb70pjMlmENOxFxci4vHvwIIN5c3KnugnGQ0+cbP78Rfu0rsXuoKOli5+8ndWD4w=
    - secure: RczizX31JVufTWYtOErNMTEDSyev+gfJJDz78oaTTAkgIAdT6mQGu1jIcFgbVlV/xLTQ2JHzQvTt5iqpdM8QJhgWfEv1AIvbQlc31qDZs8fAOzAn+/pAAbLJou4o9t2I/w46xAJ13KPqHkh2ouxKayBSMhrtJeOvn6xO2WtoclusipPbl2KSFwZfm0JDJ9XWgVzEB1c8Ykmb9yL3srL2JN6ggkWQ0g5jbh6aFx9jcWpb0Y403WCaG2unmor1u3Mr81jR8INpPF2xmsOCkvuCB09hieh/1rZqd43hlwDI4mXMqS/GQwhn6uaxZ6PtHgcWrVgAMB87MKMzteyUMqbtH2G3qPM9xzx4Z3h3do+wL5OtCNWdYwrIR8sjJ+IydiFZkSuAc3RKDbonLKsjIRNmC5EdppEkXInzjAjlHGCGDvRTkVeLTI/Em9KhmgwNbkSRqGN+BFA2yYdRY0xVyVmm26cBZ0ZHsIrRyxYwXMs/OkUgnPg//k+mYucF9GA5tmvSKsz6iYNa/vJg80wYpbZjmv0Qp9c2u6aIdYhSGkM6rCXGiOesRjJhWRqX1VPl+451fhIneXuMeZSQJ7DUzfHxxwDGdiQYYB6LIvXVRdOaZoITh/5QRToHo90U1uyiAE2ux7SbqKwLHYGRRQN8Ie5nm/P8CbG39wiSXRdB6wM9XU4=
    - secure: OFwamnCEe3UzlmjuSiive/bCVJyn/JAbmCZeDvM5NorDnlSbwWV1Kck4CQ+pkJWl4rcajhrJ0+reWseIZXkmUrv9cK9C94BrSwaY4TDKzQwFDcpS7efbS21CMCKOmCnO9OlitpBPwMz6ZHEFjH+pU2GOuQMWZ2pwVWo9qVF/e1sGAaxAuiouI4oCdiZtySrBzuiukspH0+kZbnjyxKPykPVKzaRdbJOJRqmkMWK9ZG3C+owei3A/UhlJM/Jj9WhljnyE7aaCiCaOwWsOyDJdn7oGlcanp0bD2ZD89FgWkh56DjmBCTnRkadst6+AOzpxzg0XhQsQ9uj79LrAvqqHWiBOq1oDNVqaHK2Zam0uDOc4gvavJud9HY+A4gm60DJl23wMTCiotihY9J1P2BsDm16fJrEtkMsq5SFdisK9rTl71WZyTTkrAw0uwGkp4l2ysfYdteDDj2lyIbonepfh1+wdHk0qt7R20PLrltBxji5OtwGGWNvJJ9gzEYfwASa1iMpPkH9txiwqZ4mGmepO3tiDBWtJkLQ8iCO3puTqDwjFojjgo5TH+K6XuWcONxcz+otLexl3nxTahHYzpry5M6ZhFXS3HGswwts+MtENEjHnXAeWZtCsDAsp/oC3v45B/5Np5aUmwWerXqKgGmAi1i51qVrmhb+QSXt7AaKIHeA=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: S3qIrVkA/3P82lBY0B1Ep7WBFE7req9MIU/3EoUFFynpRk/+YkjezvG2+Jyqq8NEzqWhGEXhOq8oD/QQSiWYXsOaDQY1P8TyUwabsftwxIGND2QWnC+VG/lZN0K/GB7gpUy7n08Txv3rtWPJQxyrLmYQ0qtQjbNDEO7n1uF5pO0FzTVMnttjnddFiNUhnSKvaShDT+NCtll1X+20+/qhExbkRpiuiQ5j99vMja6aLfgwDFmAmQOMY2RyqLRi+0GhMbVN57NoAcgr8P+D6/Un0Js/np2z7L0WeJfN+ow81pCogzU8wF4DySa3c9XijS2VQisZdxurp/4iteaO3EUmtTdhO+7CGTHfVGeSRxhpCr67BL1sl5QxPCpqDB4FVHB5xURxZhVgjyXV2fQkuuyZzArdxB1oZNJWKQrmXYUQyIkP4eA6zt9s20PLQSwA4ECGt3glrbWBOotd8xLLtTmLr3XtXSLl8uDusiyz2moORYBWOdrqGJul6/8rwhu5fPvWqwHVPvrDmGkuWG8lMCZ3nph0g7ULg3sYC0A8VxBNgEstfbHSKp8+ZB2O8i4WSTOyb/JxQwhyTreLUotPplTP2GrCWzI9Ig/hHXZFCyZcsGU9Sqc9vmy/d45JSSWpGQFZXg9dHNZSrhDoYi9uTNuikvg828QzIJ7/nbARGUv8pJg=
    file: "target/spt-development-cid-jms-spring-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main
